#' Looks up distances from a given table
#'
#' Takes two vectors of locations and a distance table containing location ids and looks up the distance.
#' @param a,b Location vectors
#' @param dists Table containing distances with geoids as column and row names (e.g. generated by `geoDistCalc()`)
#' @returns Gives a vector containing the distance for each pairing
#' @export
#'

cDist <- function(a, b, dists){
    dists <- mapply(function(x, y) dists[x, y], a, b)
    dists[sapply(dists, is.null)] <- NA
    dists <- unlist(dists)
    if(NA %in% dists){
        warning("NAs in output vector.")
    }
    return(dists)
}
